Artis.Siemens.HealthCareCloudServices.MVC/Areas/Admin/Controllers/DeliveryThresholdsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Artis.Siemens.HealthCareCloudServices.Domain.Models;
using Artis.Siemens.HealthCareCloudServices.EF;
using Artis.Siemens.HealthCareCloudServices.EF.Repository;
using PagedList;

namespace Artis.Siemens.HealthCareCloudServices.MVC.Areas.Admin.Controllers
{
    public class DeliveryThresholdsController : BaseController
    {
        private DeliveryThresholdRepository _repository = new DeliveryThresholdRepository();

        // GET: DeliveryThresholds
        public ActionResult Index(int? page)
        {
            string[] sessionRoles = (string[])Session["Roles"];
            if (!sessionRoles.Contains("Logistics") && !sessionRoles.Contains("Service Coordinator"))
                return Redirect("~/Home");

            else
            {
                var deliveryThresholds = _repository.All.OrderBy(i => i.DeliveryType);

                var pageNumber = page ?? 1;
                var pageData = deliveryThresholds.ToPagedList(pageNumber, Constants.PAGE_SIZE);

                ViewBag.PageData = pageData;
                return View();
            }
        }


        // GET: DeliveryThresholds/Details/5
        public ActionResult Details(int id)
        {
            DeliveryThreshold deliveryThreshold = _repository.Find(id);
            if (deliveryThreshold == null)
            {
                return HttpNotFound();
            }
            return View(deliveryThreshold);
        }

        // GET: DeliveryThresholds/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DeliveryThresholds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DeliveryType,MaxGrossWeight,MaxCombinedDimensions,WarningMessage,MaxSingleDimension")] DeliveryThreshold deliveryThreshold)
        {
            if (ModelState.IsValid)
            {
                deliveryThreshold.LastEditedPerson = CurrentUsername;
                deliveryThreshold.LastEditedTime = DateTime.Now;
                _repository.InsertOrUpdate(deliveryThreshold);
                _repository.Save();
                return RedirectToAction("Index");
            }

            return View(deliveryThreshold);
        }

        // GET: DeliveryThresholds/Edit/5
        public ActionResult Edit(int id)
        {
            DeliveryThreshold deliveryThreshold = _repository.Find(id);
            if (deliveryThreshold == null)
            {
                return HttpNotFound();
            }
            return View(deliveryThreshold);
        }

        // POST: DeliveryThresholds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DeliveryType,MaxGrossWeight,MaxCombinedDimensions,WarningMessage,MaxSingleDimension")] DeliveryThreshold deliveryThreshold)
        {
            if (ModelState.IsValid)
            {
                deliveryThreshold.LastEditedPerson = CurrentUsername;
                deliveryThreshold.LastEditedTime = DateTime.Now;
                _repository.InsertOrUpdate(deliveryThreshold, EntityState.Modified);
                _repository.Save();
                return RedirectToAction("Index");
            }
            return View(deliveryThreshold);
        }

        // GET: DeliveryThresholds/Delete/5
        public ActionResult Delete(int id)
        {
            DeliveryThreshold deliveryThreshold = _repository.Find(id);
            if (deliveryThreshold == null)
            {
                return HttpNotFound();
            }
            return View(deliveryThreshold);
        }

        // POST: DeliveryThresholds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DeliveryThreshold deliveryThreshold = _repository.Find(id);
            _repository.Delete(deliveryThreshold);
            _repository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Artis.Siemens.HealthCareCloudServices.MVC/Areas/Admin/Controllers/DropPointsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Artis.Siemens.HealthCareCloudServices.Domain.Models;
using Artis.Siemens.HealthCareCloudServices.EF;
using Artis.Siemens.HealthCareCloudServices.EF.Repository;
using PagedList;

namespace Artis.Siemens.HealthCareCloudServices.MVC.Areas.Admin.Controllers
{
    //[RoutePrefix("admin/droppoints")]
    public class DropPointsController : BaseController
    {
        private DropPointsRepository _repository = new DropPointsRepository();

        // GET: DropPoints
        //[Route]
        public ActionResult Index(int? page)
        {
            string[] sessionRoles = (string[])Session["Roles"];
            if (!sessionRoles.Contains("Logistics") && !sessionRoles.Contains("Service Coordinator"))
                return Redirect("~/Home");

            else
            {
                var dropPoints = _repository.All.OrderBy(i => i.Name1);

                var pageNumber = page ?? 1;
                var pageData = dropPoints.ToPagedList(pageNumber, Constants.PAGE_SIZE);

                ViewBag.PageData = pageData;
                return View();
            }

        }

        // GET: DropPoints/Details/5
        //[Route("details/{id}")]
        public ActionResult Details(int id)
        {
            DropPoint dropPoint = _repository.Find(id);
            if (dropPoint == null)
            {
                return HttpNotFound();
            }
            return View(dropPoint);
        }

        // GET: DropPoints/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DropPoints/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name1,Name2,Street,PostCode,Region,Remarks,CutOffBne,CutOffSyd,CutOffMel,CutOffAdl,CutOffPer,Long,LastEditedTime,LastEditedPerson,Lat,Suburb")] DropPoint dropPoint)
        {
            if (ModelState.IsValid)
            {
                dropPoint.LastEditedPerson = CurrentUsername;
                dropPoint.LastEditedTime = DateTime.Now;
                _repository.InsertOrUpdate(dropPoint, EntityState.Added);
                _repository.Save();
                return RedirectToAction("Index");
            }

            return View(dropPoint);
        }

        // GET: DropPoints/Edit/5
        //[Route("admin/droppoints/edit/{id}")]
        //[Route("edit/{id}")]
        public ActionResult Edit(int id)
        {
            DropPoint dropPoint = _repository.Find(id);
            if (dropPoint == null)
            {
                return HttpNotFound();
            }
            return View(dropPoint);
        }

        // POST: DropPoints/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Route("edit/{id}")]
        public ActionResult Edit([Bind(Include = "Id,Name1,Name2,Street,PostCode,Region,Remarks,CutOffBne,CutOffSyd,CutOffMel,CutOffAdl,CutOffPer,Long,LastEditedTime,LastEditedPerson,Lat,Suburb")] DropPoint dropPoint)
        {
            if (ModelState.IsValid)
            {
                dropPoint.LastEditedPerson = CurrentUsername;
                dropPoint.LastEditedTime = DateTime.Now;
                _repository.InsertOrUpdate(dropPoint, EntityState.Modified);
                _repository.Save();
                return RedirectToAction("Index");
            }
            return View(dropPoint);
        }

        // GET: DropPoints/Delete/5
        public ActionResult Delete(int id)
        {
            DropPoint dropPoint = _repository.Find(id);
            if (dropPoint == null)
            {
                return HttpNotFound();
            }
            return View(dropPoint);
        }

        // POST: DropPoints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DropPoint dropPoint = _repository.Find(id);
            _repository.Delete(dropPoint);
            _repository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _repository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Artis.Siemens.HealthCareCloudServices.MVC/Areas/Order/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Artis.Siemens.HealthCareCloudServices.MVC.Areas.Order.Controllers
{
    //[Authorize]
    public class CreateController : Controller
    {
        // GET: Order/Create
        //[Authorize]
        public ActionResult Index()
        {
            var orderId = Request.QueryString["id"];
            return View();
        }
    }
}

Artis.Siemens.HealthCareCloudServices.MVC/Areas/Order/Controllers/TrackController.cs
using Artis.Siemens.HealthCareCloudServices.MVC.Areas.Admin.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Artis.Siemens.HealthCareCloudServices.MVC.Areas.Order.Controllers
{
    public class TrackController : BaseController
    {
        // GET: Order/Track
        public ActionResult Index()
        {
            ViewBag.LoginId = Session["LoginId"].ToString();
            return View();
        }
    }
}

Artis.Siemens.HealthCareCloudServices.MVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    string appBase = ("http://" + Request.Url.Authority +
    Request.ApplicationPath.TrimEnd('/') + "/").ToLower();
}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SIEMENS Healthcare Services</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="~/Content/chosen.min.css" />
    <link rel="stylesheet" href="~/Content/bootstrap-timepicker.css" />
    <link rel="stylesheet" href="~/Content/bootstrap-datepicker.min.css" />

    <script>
        var appBase = '@appBase';
    </script>
    <meta name="description" content="@ViewBag.Title - SIEMENS Healthcare Services" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="~/">
                    <img src="~/Images/siemens.gif" />
                </a>

                @*@Html.ActionLink("SIEMENS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="navbar-brand" href="~/">
                            <i class="fa fa-home"></i>
                        </a>
                    </li>
                    <li>@Html.ActionLink("Create Delivery Order", "Index", "Create", new { Area = "Order" }, new { })</li>
                    <li>@Html.ActionLink("Track Order Status", "Index", "Track", new { Area = "Order" }, new { })</li>
                    @{
                        if (Session["Roles"] != null)
                        {
                            string[] sessionRoles = (string[])Session["Roles"];

                            if (sessionRoles.Contains("Logistics"))         // HAS to contain LOGISTICS for SETUP
                            {
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="False">Setup <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        @{
                                            if (sessionRoles.Contains("Logistics"))
                                            {
                                                <li>@Html.ActionLink("Edit Drop Points", "Index", "DropPoints", new { Area = "Admin" }, new { })</li>
                                            }
                                        }
                                        @{
                                            if (sessionRoles.Contains("Logistics") && sessionRoles.Contains("Service Coordinator"))
                                            {
                                                <li>@Html.ActionLink("Int Flight Dest Mapping", "Index", "InternationalDestinations", new { Area = "Admin" }, new { })</li>
                                            }
                                        }
                                        @{
                                            if (sessionRoles.Contains("Logistics"))
                                            {
                                                <li>@Html.ActionLink("Int Flight Sched & Cutoff", "Index", "InternationalFlightsCutOffs", new { Area = "Admin" }, new { })</li>
                                            }
                                        }
                                        @{
                                            if (sessionRoles.Contains("Logistics"))
                                            {
                                                <li>@Html.ActionLink("Special Delivery Thresholds", "Index", "DeliveryThresholds", new { Area = "Admin" }, new { })</li>
                                            }
                                        }
                                        @{
                                            if (sessionRoles.Contains("Logistics"))
                                            {
                                                <li>@Html.ActionLink("Lead Time & Cost Matrix", "Index", "LeadTimeCostFormulas", new { Area = "Admin" }, new { })</li>
                                            }
                                        }
                                        @{
                                            if (sessionRoles.Contains("Logistics"))
                                            {
                                                <li>@Html.ActionLink("IBase Delivery Details", "Index", "IBASEDeliveryDetails", new { Area = "Admin" }, new { })</li>
                                            }
                                        }
                                    </ul>
                                </li>
                                                }
                                            }
                    }
                    }
                </ul>
                @{
                    var userID = "";
                    var displayName = "";

                    if (Session["LoginId"] != null)
                    {
                        userID = Session["LoginId"].ToString();
                        displayName = Session["DisplayName"].ToString();
                    }
                }
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="~/Account/SignOut"><i class="fa fa-sign-out"></i> @displayName</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SIEMENS Healthcare Services</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")

    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    <script src="~/Scripts/chosen.jquery.min.js"></script>
    <script src="~/Scripts/jasny-bootstrap.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>

    @RenderSection("scripts", required: false)

    <!-- include all the APP JS files - using a version tag'ing to make sure of NO caching -->
    <script src="~/app/SpareParts.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/core/module.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/core/directives/linkAction.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/core/directives/loadingIndicator.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/core/directives/stopEvent.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/core/directives/validationResponse.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/core/services/empService.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/core/services/orderEntryService.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>

    <script src="~/app/modules/OrderEntry/module.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/OrderEntry/controllers/DeliveryCtrl.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/OrderEntry/controllers/OrderCtrl.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/OrderEntry/controllers/OrderItemsCtrl.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>

    <script src="~/app/modules/OrderConfirm/module.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/OrderConfirm/controllers/OrderDetailCtrl.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/OrderConfirm/services/orderConfirmService.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>

    <script src="~/app/modules/OrderTrack/module.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/OrderTrack/services/orderTrackService.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>
    <script src="~/app/modules/OrderTrack/controllers/orderTrackController.js?v=@ViewContext.Controller.GetType().Assembly.GetName().Version"></script>

    <script>
        angular.module('SpareParts', ['SpareParts.Core', 'SpareParts.OrderEntry', 'SpareParts.OrderConfirm', 'SpareParts.OrderTrack']);
    </script>
</body>
</html>